version: 2
jobs:
  build:
    working_directory: ~/cec
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install node testing dependencies
          command: 'sudo npm install -g testcafe'
      - run:
          name: Run tests
          command: 'testcafe "chrome:headless" tests/button_test.js'
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          path:
            - .
