version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install node testing dependencies
          command: 'sudo npm install -g testcafe'
      - run:
          name: Run tests
          command: 'testcafe "chrome:headless" tests/button_test.js'
